### ISSUE TITLE
KeyError: 'stats'

### ISSUE THREAD

**Issue by key-glock** [seidapps/nft-top-collection-stats#1]
Hi :)
I change 'stats' to 'statsV2' and it work, but have next problem: KeyError: 'marketCap' 
how fix, help, thx

<img width="486" alt="Снимок экрана 2022-02-08 в 00 58 15" src="https://user-images.githubusercontent.com/94188701/152886438-9e97bd47-69e2-42c7-81b8-f0416f36f757.png">

**Comment by seidapps** [comment]
Awesome, thank you! Updated to statsV2 :)
